feat: implement custom keyboard shortcuts
This feature was requested in

https://github.com/ayushnix/tessen/issues/30

and

https://github.com/ayushnix/tessen/issues/32

This feature is inspired from rofi-pass. However, rofi-pass implemented
this feature only for rofi by using its command line flags. Since tessen
intends to work with multiple dmenu scripts, I've mapped the actions to
exit codes instead. This would allow users to map exit codes greater
than 10 to whatever keybindings they prefer.

diff --git a/tessen b/tessen
--- a/tessen
+++ b/tessen
@@ -28,6 +28,7 @@ tsn_delay=100
 tsn_config="${XDG_CONFIG_HOME:-$HOME/.config}"/tessen/config
 # variables with sensitive data which will be manually unset using _clear
 declare _TSN_PASSFILE _TSN_USERNAME _TSN_PASSWORD _TSN_URL _TSN_AUTOTYPE chosen_key
+declare -i _EXIT_STATUS
 declare -A _TSN_PASSDATA
 
 # FIRST MENU: generate a list of pass files, let the user select one
@@ -48,6 +49,7 @@ get_pass_files() {
 
   _TSN_PASSFILE="$(printf "%s\n" "${tmp_pass_files[@]}" \
     | "$dmenu_backend" "${dmenu_backend_opts[@]}")"
+  _EXIT_STATUS="$?"
 
   # instead of searching through the tmp_pass_files array for valid selection,
   # we check if the corresponding file is present
@@ -67,6 +69,7 @@ get_gopass_files() {
 
   _TSN_PASSFILE="$(printf "%s\n" "${tmp_gopass_files[@]}" \
     | "$dmenu_backend" "${dmenu_backend_opts[@]}")"
+  _EXIT_STATUS="$?"
 
   if [[ -z $_TSN_PASSFILE ]]; then
     _die
@@ -149,6 +152,20 @@ get_pass_data() {
   fi
 
   unset -v passdata keyval_regex otp_regex idx key val
+}
+
+# map custom actions to specific dmenu exit codes
+custom_keyb_action() {
+  case "$_EXIT_STATUS" in
+    10) auto_type_def ;;
+    11) auto_type "$_TSN_USERNAME" ;;
+    12) auto_type "$_TSN_PASSWORD" ;;
+    13) key_open_url ;;
+    14) wld_copy "$_TSN_USERNAME" ;;
+    15) wld_copy "$_TSN_PASSWORD" ;;
+    16) wld_copy "$_TSN_URL" ;;
+    *) _die "unmapped exit code detected" ;;
+  esac
 }
 
 # SECOND MENU: show a list of possible keys to choose from for autotyping or
@@ -797,6 +814,10 @@ main() {
     get_gopass_files
   fi
   get_pass_data
+  if [[ "$_EXIT_STATUS" -ge 10 ]]; then
+    custom_keyb_action
+    exit 0
+  fi
   key_menu
   trap - EXIT TERM INT
 }
